# Uncomment the next line to define a global platform for your project

 platform :ios, '9.0'

target 'TatabApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

 pod 'AFNetworking', '~> 2.5.0'
 
 pod 'TPKeyboardAvoiding', '~> 1.3'
  pod 'SDWebImage', '~> 4.1'
  pod 'SWRevealViewController', '~> 2.3'

  # Pods for TatabApp

  pod 'XMPPFramework', :git => "https://github.com/robbiehanson/XMPPFramework.git", :branch => 'master'



  # Pods for TatabApp

  target 'TatabAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
